<PlayListScreen>:
    listview: listview

    BoxLayout:
        orientation: 'vertical'
        ListView:
            id: listview
            size_hint_y: 0.9
            row_height: "50dp"
        BoxLayout:
            size_hint_y: 0.1
            orientation: 'horizontal'
            padding: 10, 10, 10, 10
            Button:
                text: 'Back'
                on_release: root.ctrl.show_main()

